###

POST http://localhost:8000/query
Content-Type: application/json

{"text": "what do rabbits eat?"}

###

POST http://localhost:8000/query
Content-Type: application/json

{"text": "what do rabbits eat?"}

###

