openapi: 3.0.0
info:
  title: Salable API
  version: v2
  description: |
    # Salable API
    
    Salable is a comprehensive solution tailored for SaaS businesses, streamlining the design and management of pricing models, subscriptions, and licensing.
    
    This documentation is designed to guide you through integrating with Salable's features via our REST API.

    ## HTTP Endpoints
    
     - Use HTTP endpoints to access different features.
     - Send requests using JSON and receive JSON responses.
    
    ## Authentication

    Secure your requests by sending your api key on the `x-api-key` request header for authentication. Or, if the endpoint supports it, a session token with the correct scope sent on the `Authorization` request header.
    
    The API Key can be created in the Salable dashboard. Select only the scopes you need will to access. If you're using this in combination with our SDKs be sure to only select read only scopes.

    > NOTE: If you'd like to use test mode via the API, make sure to use an API key generated in test mode (prefixed with `test_`).

    ## Quick Start
    
    To get up and running, you need to work through the following steps.
    
    - Set up a Salable Account and Organization
    - Connect Stripe to Salable (You can skip this for a free product)
    - Build your products and plans
    - Generate your API key
    - Make your first API call with the request header "version" set to "v2" 
    
    ## HTTP Status Codes

    We use standard HTTP status codes for both success and failure responses.

    | HTTP Code | What it means                                                                                                                                           |
    | --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
    | 200       | The request was successful and the action has been completed.                                                                                           |
    | 201       | This will be sent for the successful completion of POST requests and indicates that the new item was created, eg. a new license.                        |
    | 204       | The request was successful, no content to returned.                                                                                                     |
    | 206       | The request was partially successful.                                                                                                                   |
    | 400       | There was a request validation error and the request couldn't be completed.                                                                             |
    | 401       | There was an authentication problem. If you get this error you should make sure your API key is included in the `x-api-key` header. Or, your session token is valid for the endpoint being requested and it has not expired.                     |
    | 403       | There was an authorisation issue. If you get this error you should check your API key has the correct scopes and that you're in the right organisation  |
    | 404       | The request couldn't be completed as the requested resource(s) doesn't exist.                                                                           |
    | 500       | A problem on our side. If you experience one of these errors, reach out to us and we will help.                                                         |

servers:
  - url: https://api.salable.app

components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
    sessionToken:
      type: sessionToken
      name: Authorization
      in: header

tags:
  - name: Products
    description: Operations related to products.
  - name: Plans
    description: Operations related to plans.
  - name: Pricing Tables
    description: Operations related to pricing tables.
  - name: Subscriptions
    description: Operations related to licenses.
  - name: Licenses
    description: Operations related to licenses.
  - name: Usage
    description: Operations related to usage.
  - name: Events
    description: Operations related to events.
  - name: Checkout
    description: Operations related to checkout.

paths:
  /products:
    get:
      summary: Get products
      operationId: getProducts
      description: Retrieves a list of all products
      tags:
        - Products
      security:
        - apiKey: [ "products:read" ]
  /products/{productUuid}:
    get:
      summary: Get a product
      operationId: getProductByUuid
      description: |
        Retrieves a specific product by its UUID. 
        By default, the response does not contain any relational data. If you want to expand the relational data, you can do so with the `expand` query parameter.
      tags:
        - Products
      security:
        - apiKey: [ "products:read" ]
  /products/{productUuid}/plans:
    get:
      summary: Get all plans of a product
      operationId: getProductPlans
      description: |
        Retrieves all the plans associated with a specific product.
        By default, the response does not contain any relational data. If you want to expand the relational data, you can do so with the `expand` query parameter.
      tags:
        - Products
      security:
        - apiKey: [ "plans:read" ]
  /products/{productUuid}/pricingtable:
    get:
      summary: Get product pricing table
      operationId: getProductPricingTable
      description: |
        Retrieves the pricing table of a specific product.
      tags:
        - Products
      security:
        - apiKey: [ "pricing-tables:read" ]
        - sessionToken: [ "web-components:pricing-table" ]
  /products/{productUuid}/features:
    get:
      summary: Get product features
      description: Retrieve the list of features for a product
      operationId: getProductFeatures
      tags:
        - Products
      security:
        - apiKey: [ "features:read" ]
  /products/{productUuid}/currencies:
    get:
      summary: Get product currencies
      description: Retrieve the list of currencies for a product
      operationId: getProductCurrencies
      tags:
        - Products
      security:
        - apiKey: [ "currencies:read" ]
  /products/{productUuid}/capabilities:
    get:
      summary: Get product capabilities
      description: Retrieve the list of capabilities for a product
      operationId: getProductCapabilities
      tags:
        - Products
      security:
        - apiKey: [ "capabilities:read" ]
  /plans/{planUuid}:
    get:
      summary: Get a plan
      operationId: getPlanByUuid
      description: |
        Retrieves information about a plan by its UUID.
        By default, the response does not contain any relational data. If you want to expand the relational data, you can do so with the `expand` query parameter.
      tags:
        - Plans
      security:
        - apiKey: [ "plans:read" ]
        - sessionToken: [ "web-components:checkout" ]
  /plans/{planUuid}/features:
    get:
      summary: Get plan features
      description: Retrieve the list of features for a specific plan
      operationId: getPlanFeatures
      tags:
        - Plans
      security:
        - apiKey: [ "features:read" ]
  /plans/{planUuid}/currencies:
    get:
      summary: Get plan currencies
      description: Retrieve the list of currencies for a specific plan
      operationId: getPlanCurrencies
      tags:
        - Plans
      security:
        - apiKey: [ "currencies:read" ]
  /plans/{planUuid}/checkoutlink:
    get:
      summary: Get a checkout link for a plan
      operationId: getPlanCheckoutLink
      description: Retrieves a checkout link for a specific plan. The checkout link can be used by customers to purchase the plan.
      tags:
        - Plans
      security:
        - apiKey: [ "plans:read" ]
        - sessionToken: [ "web-components:pricing-table" ]
  /plans/{planUuid}/capabilities:
    get:
      summary: Get plan capabilities
      description: Retrieve the list of capabilities for a specific plan
      operationId: getPlanCapabilities
      tags:
        - Plans
      security:
        - apiKey: [ "capabilities:read" ]
  /licenses:
    post:
      summary: Create a license
      operationId: createLicense
      description: Create one or many ad hoc Licenses to give the specified granteeIds access to features. Per seat ad hoc licenses are currently not supported. If you are incrementing seats on a paid subscription use the [increment seats](#tag/Subscriptions/operation/incrementSubscriptionSeats) endpoint instead.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:write" ]
        - sessionToken: [ "web-components:pricing-table" ]
    put:
      summary: Batch update licenses
      operationId: updateLicenses
      description: Performs a batch update of licenses.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:write" ]
    get:
      summary: Get licenses
      operationId: getLicenses
      description: Retrieves a list of all licenses.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
  /licenses/count:
    get:
      summary: Get the count of licenses
      operationId: getLicensesCount
      description: Returns the count of all licenses including counts for assigned and unassigned licenses.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
  /licenses/{licenseUuid}:
    get:
      summary: Get a License
      operationId: getLicenseByUuid
      description: Fetch the details of a specific license using its UUID. If additional specific details are required, use the optional 'expand' query parameter to include relational data such as associated subscription details, pricing plans, product details, etc.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
    put:
      summary: Update a license
      operationId: updateLicense
      description: Set or unset the granteeId of a license.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:write" ]
    delete:
      summary: Cancel an ad hoc License
      operationId: cancelLicense
      description: |
        Cancel an ad hoc license, this will set the status to `CANCELED`
        
        Does not cancel subscription, only use for canceling ad hoc licenses.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:write" ]
  /licenses/check:
    get:
      summary: Check a grantee(s) licenses
      operationId: getLicenseCheck
      description: Retrieves the capabilities the grantee(s) have access to.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
  /licenses/purchaser:
    get:
      summary: Get licenses by purchaser
      operationId: getLicensesByPurchaser
      description: Retrieves an array of licenses for a purchaser
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
  /licenses/granteeId/{granteeId}:
    get:
      summary: Get licenses by granteeId
      operationId: getLicensesByGranteeId
      description: Retrieves a list of licenses for a grantee
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:read" ]
  /licenses/cancel:
    post:
      summary: Cancel many ad hoc licenses
      operationId: cancelLicenses
      description: |
        Cancels ad hoc Licenses with using an array of licenseUuids.
        
        Does not cancel subscription, only use for canceling ad hoc licenses.
      tags:
        - Licenses
      security:
        - apiKey: [ "licenses:write" ]
  /subscriptions:
    get:
      summary: Get subscriptions
      operationId: getSubscriptions
      description: Retrieves a list of all subscriptions.
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:read" ]
  /subscriptions/{subscriptionUuid}:
    get:
      summary: Get a subscription
      operationId: getSubscriptionByUuid
      description: |
        Retrieves the subscription data based on the UUID.
        By default, the response does not contain any relational data. If you want to expand the relational data, you can do so with the `expand` query parameter.
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:read" ]
  /subscriptions/{subscriptionUuid}/change-plan:
    put:
      summary: Change a Subscription's Plan
      operationId: changeSubscriptionsPlan
      description: |
        Changes a subscription's plan based on UUID. If the subscription is usage based the requested subscription will be canceled and a new subscription will be created on the plan you are changing to.
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:write" ]
  /subscriptions/{subscriptionUuid}/invoices:
    get:
      summary: Get subscription invoices
      operationId: getSubscriptionInvoices
      description: Retrieves a list of invoices for a subscription
      tags:
        - Subscriptions
      security:
        - apiKey: [ "billing:read" ]
        - sessionToken: [ "web-components:invoices" ]
  /subscriptions/{subscriptionUuid}/updateplan/listplans:
    get:
      summary: Get plans that a subscribed user can switch to
      operationId: getSubscriptionUpdatablePlans
      description: Retrieves a list of available plans that a subscribed user can switch to
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:read" ]
  /subscriptions/{subscriptionUuid}/cancel:
    put:
      summary: Cancel a subscription
      description: |
        Cancels a subscription by providing the `subscriptionUuid`
        It will cancel immediately or at the end of the Subscription based on value of the `when` query parameter.
      operationId: cancelSubscription
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:write" ]
  /subscriptions/{subscriptionUuid}/updatepaymentlink:
    get:
      summary: Get an update payment link
      operationId: getSubscriptionUpdatePaymentLink
      description: |
        Retrieves the update payment link for a specific subscription. 
        The link opens up a management portal for your payment integration that will have an option for the customer to update their payment details.
      tags:
        - Subscriptions
      security:
        - apiKey: [ "billing:write" ]
  /subscriptions/{subscriptionUuid}/customer-portal:
    get:
      summary: Get a customer portal link
      operationId: getSubscriptionCustomerPortalLink
      description: |
        Retrieves the customer portal link for a subscription.
        The link opens up a subscription management portal for your payment integration that will have an options for the customer to manage their subscription.
      tags:
        - Subscriptions
      security:
        - apiKey: [ "billing:write" ]
  /subscriptions/{subscriptionUuid}/cancelpaymentlink:
    get:
      summary: Get a cancel subscription link
      description: |
        Retrieves the cancel subscription link for a specific subscription. 
        The link opens up a subscription management portal for your payment integration that will have an option for the customer to cancel the subscription.
      operationId: getSubscriptionCancelLink
      tags:
        - Subscriptions
      security:
        - apiKey: [ "billing:write" ]
  /subscriptions/{subscriptionUuid}/payment-method:
    get:
      summary: Get payment method
      description: Retrieves the payment method used to pay for a subscription.
      operationId: getSubscriptionPaymentMethod
      tags:
        - Subscriptions
      security:
        - apiKey: [ "billing:read" ]
  /subscriptions/{subscriptionUuid}/reactivate:
    put:
      summary: Reactivate a Subscription
      description: Reactivate a Subscription's scheduled cancellation before the billing period has passed. If the billing period has passed and the Subscription has already been canceled please create a new Subscription.
      operationId: getSubscriptionReactivate
      tags:
        - Subscriptions
      security:
        - apiKey: [ "subscriptions:write" ]
  /subscriptions/{subscriptionUuid}/seats:
    post:
      summary: Increment quantity of seats on a subscription.
      description: Incrementing will create unassigned licenses.
      operationId: incrementSubscriptionSeats
      tags:
        - Subscriptions
      security:
        - apiKey: [ "licenses:write" ]
    put:
      summary: Decrement quantity of seats on a subscription.
      description: Decrementing will only remove unassigned licenses.
      operationId: decrementSubscriptionSeats
      tags:
        - Subscriptions
      security:
        - apiKey: [ "licenses:write" ]
  /usage:
    get:
      summary: Get all usage records for grantee
      operationId: getLicenseUsage
      description: Retrieves all usage records for grantee's metered licenses.
      tags:
        - Usage
      security:
        - apiKey: [ "usage:read" ]
    put:
      summary: Updates a license's usage
      operationId: updateLicenseUsage
      description: Updates the usage on a license by incrementing its value.
      tags:
        - Usage
      security:
        - apiKey: [ "usage:write" ]
  /usage/current:
    get:
      summary: Get current usage record for grantee on plan
      operationId: getCurrentLicenseUsage
      description: Retrieves the current usage record for a metered license.
      tags:
        - Usage
      security:
        - apiKey: [ "usage:read" ]
  /sessions:
    post:
      summary: Create a new session
      operationId: createSession
      description: Creates a new session to use with the Salable web components
      tags:
        - Sessions
      security:
        - apiKey: [ "sessions:write" ]
  /events/{eventUuid}:
    get:
      summary: Get a event
      operationId: getEventByUuid
      description: |
        Retrieves an event by its UUID. Events keep track of the progress of asynchronous tasks which rely on receiving webhooks or additional processing to complete.
      tags:
        - Events
      security:
        - apiKey: [ "events:read" ]
  /pricing-tables/{pricingTableUuid}:
    get:
      summary: Get a pricing table
      operationId: getPricingTableByUuid
      description: Retrieves a pricing table by its UUID. This returns all necessary data on a Pricing Table to be able to display it.
      tags:
        - Pricing Tables
      security:
        - apiKey: [ "pricing-tables:read" ]
        - sessionToken: [ "web-components:pricing-table" ]
  /checkout/create-subscription:
    post:
      summary: Create a Stripe subscription with a payment intent
      operationId: checkoutCreateSubscription
      description: |
        Creates a Stripe subscription with an `incomplete` status and returns the `latest_invoice.payment_intent.client_secret` necessary for Stripe Elements and Salable Checkout component. 
        This status changes to `active` once a payment method is successfully processed.
      tags:
        - Checkout
      security:
        - apiKey: [ "subscriptions:write" ]
        - sessionToken: [ "web-components:checkout" ]
  /checkout/create-intent:
    post:
      summary: Create a Stripe Setup Intent
      operationId: checkoutCreateIntent
      description: |
        Creates a Stripe Setup Intent and returns the `clientSecret` required for use with Stripe Elements and the Salable Checkout component. 
      tags:
        - Checkout
      security:
        - sessionToken: [ "web-components:checkout" ]